### ISSUE TITLE
Migrate wiki page

### ISSUE THREAD

**Issue by wvanbergen** [barttenbrinke/munin-plugins-rails#1]
Migrate the current wiki page in the r-l-a wiki and check if the information is still correct with the new repository. See http://wiki.github.com/wvanbergen/request-log-analyzer/munin

**Comment by barttenbrinke** [comment]
Woot fans :)

**Comment by barttenbrinke** [comment]
copy pasted first version

**Comment by barttenbrinke** [comment]
updated
