### ISSUE TITLE
Installation: "cp: munin-plugins-rails/rails_requests: No such file or directory" -- What am I doing wrong?

### ISSUE THREAD

**Issue by alexsherstinsky** [barttenbrinke/munin-plugins-rails#10]
Hi, I ran git clone git://github.com/barttenbrinke/munin-plugins-rails.git according to the installation instructions in README.rdoc and munin-plugins-rails appeared as expected.  However, cannot run the next command, 'cp munin-plugins-rails/rails_requests /usr/share/munin/plugins/', because there is no such file 'rails_requests' in 'munin-plugins-rails'.  Could someone please tell me what I am doing wrong?  Thanks a lot!  --Alex

**Comment by barttenbrinke** [comment]
Hi,
we are in the process of refactoring munin-plugins-rails into a gem. at the moment this is almost working, but not quite :). If you want the old version, please checkout https://github.com/barttenbrinke/munin-plugins-rails/tree/stable . I'll be changing the readme in master asap to reflect this.

Greetings, Bart

**Comment by alexsherstinsky** [comment]
Hi, Bart:

Thank you very much for your response.  What is the best way to get notified when the new gem becomes available?  (I will use the old version until then.)

Thanks, and Regards,
--Alex

**Comment by barttenbrinke** [comment]
Hi Alex,
we are working on docs and testing it on some servers. If you could help with that, that would be great!
Greetings, Bart

**Comment by alexsherstinsky** [comment]
Hi, Bart:

Please tell us how we can help.  I am copying my colleague Eugene as I will be on vacation during the week of April 4th.

Thank you,
--Alex
------Original Message------

**Comment by ebertech** [comment]
Hi

A quick rundown: 

You should be able to install the gem with:

gem install munin-plugins-rails

After that you can run:

sudo request-log-analyzer-munin install

Which will install the passenger plugins into /etc/munin/plugins 

To add an app use 

sudo request-log-analyzer-munin add app_name path_to_log_file

This will create a set of plugins for your app so with the prefix app_name. This prefix should be free of spaces. As Bart mentioned, we're updating the docs but I wanted to get you up and running in the meantime.

**Comment by alexsherstinsky** [comment]
Hello:

I will give it a shot today and let you know if I run into any problems.

Thank you,
--Alex

**Comment by alexsherstinsky** [comment]
By the way,

Do I have to first run
sudo gem install request-log-analyzer
before running
sudo gem install munin-plugins-rails

or will the latter automatically install the former?

Thank you,
--Alex

**Comment by ebertech** [comment]
That's a good point, you need to run it manually now, I'll add it to the dependencies.

**Comment by alexsherstinsky** [comment]
No problem -- great to know.  Will let you know how it goes and/or if I need
more help.  Thank you, --Alex

**Comment by alexsherstinsky** [comment]
Hi:

Here are a few more questions.

1) Do I still have to add
[rails_requests]
    env.log_file '/path/to/production.log'
    user www-data
    command /usr/local/bin/ruby %c

to 'plugin-conf.d/munin-node'?

2) Anything else to add to 'plugin-conf.d/munin-node' in order to get the monitoring for passenger and my application?

3) Is the username 'www-data' going to work without me adding that user on the OS (I am using CentOS-5.5)?

Thank you,
--Alex

**Comment by barttenbrinke** [comment]
Added basic readme to help things along :)

**Comment by barttenbrinke** [comment]
1) Yes, if you are doing things manually, otherwise running:

  request-log-analyzer-munin MyApp /path/to/production.log

should fix everything. If not, we have our first bug :)

2) Yes, if you are doing things manually, otherwise running:

  request-log-analyzer-munin install

should fix everything. If not, we have our second bug :)

3) Passenger-status usually requires root to run, as it inspects apache. The rails monitoring should work if the log-file can be read by www-data.

**Comment by ebertech** [comment]
Hi, I've updated the README some more.

**Comment by alexsherstinsky** [comment]
Hello:

1) I ran 'sudo request-log-analyzer-munin MyApp /path/to/production.log'
However, 'plugin-conf.d/munin-node' remained unchanged.
2) What exactly should I add in order to have everything that request-log-analyzer-munin offers monitored as part of my munin installation?  I did not see anything added to 'plugin-conf.d/munin-node'  (please see [1] above).
3) I do not have the user 'www-data' on my system.  Should I add it?  On the other hand, I have the user 'munin'.  Could I simply use 'munin' as the user instead of 'www-data'?

Thank you very much for you help, and sorry if the questions are too basic.
--Alex

**Comment by ebertech** [comment]
Hi,

I've update the README to explain this. I'm not a huge fan of a monolithic plugin-conf.d/munin-node so each plugin gets it's own file in plugin-conf.d. That way there's less chance for accidental breaking.

**Comment by alexsherstinsky** [comment]
Hello again:

I take it back.  Even though 'plugin-conf.d/munin-node' was not changed, the following new files appeared in '/etc/munin/plugin-conf.d':

-rw-r--r-- 1 root root  273 Mar 28 16:25 MyApp_munin_rails_database_time
-rw-r--r-- 1 root root  279 Mar 28 16:25 MyApp_munin_rails_request_duration
-rw-r--r-- 1 root root  273 Mar 28 16:25 MyApp_munin_rails_request_error
-rw-r--r-- 1 root root  263 Mar 28 16:25 MyApp_munin_rails_requests
-rw-r--r-- 1 root root  279 Mar 28 16:25 MyApp_munin_rails_view_render_time
-rw-r--r-- 1 root root  227 Mar 28 16:23 munin_passenger_memory_stats
-rw-r--r-- 1 root root  220 Mar 28 16:23 munin_passenger_queue
-rw-r--r-- 1 root root  221 Mar 28 16:23 munin_passenger_status

Please let me know if this is expected and/or if I should do anything differently.

Thank you,
--Alex

**Comment by ebertech** [comment]
Hi, nope those are as expected. See the updated README and my comments above.

**Comment by alexsherstinsky** [comment]
Furthermore, the new files are using the user 'root', which is exactly right for my system.  Question, assuming that munin will pick up these files, should I just restart munin-node now?  Thank you, --Alex

**Comment by ebertech** [comment]
Hi, yes you need to restart munin-node.

**Comment by alexsherstinsky** [comment]
Hi!

It's working now.  However, what would be really nice is if all graphs for MyApp could appear under the same heading (e.g., 'MyApp_log_analyzer', or simply 'MyApp').  As it stands now, every entry appears in the munin group that I am monitoring:

```
*MyGroupName [ apache MyApp_munin_rails_database_time MyApp_munin_rails_request_duration MyApp_munin_rails_request_error MyApp_munin_rails_requests MyApp_munin_rails_view_render_time disk exim memcache munin mysql network nfs passenger processes system time ]
```

As you can see, there are too many with 'MyApp' prefix, which could be combined.

Thank you very much!
--Alex

**Comment by barttenbrinke** [comment]
That should be doable :)

**Comment by alexsherstinsky** [comment]
And when might I get it? :)

**Comment by ebertech** [comment]
Hi, maybe I'm missing something. It's supposed to keep everything under one category. Can you send me a copy of /etc/munin/plugin-conf.d/MyApp_*? It should have a line in there that says 

env.graph_category MyApp

**Comment by alexsherstinsky** [comment]
Hi:

Here is the listing of my '/etc/munin/plugin-conf.d':

MyServer /etc/munin: ls plugin-conf.d/
MyApp_rails_database_time     MyApp_munin_rails_request_error  MyApp_munin_rails_view_render_time  munin-node                    munin_passenger_queue   postfix
MyApp_munin_rails_request_duration  MyApp_munin_rails_requests       hddtemp_smartctl                        munin_passenger_memory_stats  munin_passenger_status  sendmail

The files with the prefix 'MyApp' and 'munin_passenger' were added as part of the installation of 'munin-plugins-rails'.

Here are the contents of the '/etc/munin/plugin-conf.d/MyApp_munin_rails_requests' file:
[MyApp_munin_rails_requests]  
env.log_file /home/MySpecialUser/AnotherDir/YetAnotherDir/MyApp/log/test.log
user root
command /usr/local/bin/ruby %c
env.request_log_analyzer /usr/local/bin/request-log-analyzer  
env.graph_category MyApp_munin_rails_requests

Other files have the similar content.  Please note that the last line adapts to the given stat being monitored, which is probably why there are as many different categories.

Thank you very much,
--Alex

**Comment by ebertech** [comment]
That's the problem. I just fixed and pushed it. You can manually edit this for now, just change env.graph_category to be whatever category you want and restart munin-node.

**Comment by alexsherstinsky** [comment]
Hi, that's great!  I am going to delete my installation and install it fresh.  I will let you know if I encounter any challenges.  Thanks! --Alex

**Comment by ebertech** [comment]
ok, the gem JUST got pushed. Make sure you have version 0.2.11 installed.

**Comment by alexsherstinsky** [comment]
Hello:

Yes -- installed the gem munin-plugins-rails version 0.2.11 (which pulled in request-log-analyzer-1.10.1).

Everything works great now!

Later, I will monitor how munin displays the graphs and also try to set up some warnings.  I will let you know if I run into any issues with those.

Thank you very much for your help.

Sincerely, --Alex
