### ISSUE TITLE
HTML report

### ISSUE THREAD

**Issue by fabianoalmeida** [barttenbrinke/munin-plugins-rails#17]
Is there any way to see all reports created by this plugin in my own app? Like an HTML file.

If what I'm saying it's a foolishness, how can I see all the reports?

Thanks in advance!

**Comment by barttenbrinke** [comment]
Hi,

I think the main question here is: do you know what Munin is and how it works?

If not: you need to install Munin on a linux server to get these plugins running. Munin is an application that monitors and graphs statistics about devices in your network: http://munin-monitoring.org or http://www.amazon.com/Instant-Munin-Plugin-Starter-Brinke/dp/1849696748 .

If you do: I think the best option is to assign Munin it's own vhost and have it running on munin.yourapp.com .

**Comment by fabianoalmeida** [comment]
Hmmm... Thanks @barttenbrinke.

Just for understand... I use Munin to collect informations to show as a report, send to mail, whatever. Am I correct?

If I'm correct, do you know a lib that can give me a report (with graphs) of my production log?

Thanks again.

**Comment by barttenbrinke** [comment]
There are a couple of options

1) You can set up a cronjob that will email you the html output of request-log-analyzer

2) If you only have access to the logs, you should take a look at [scoutapp](https://scoutapp.com) which is powered by request-log-analyzer. 

3) If you have access to the app you can set up [new relic](https://newrelic.com). This is probably the simplest, but also the most expensive option.

**Comment by fabianoalmeida** [comment]
Thank you so much @barttenbrinke!

**Comment by barttenbrinke** [comment]
Happy monitoring :)
