### ISSUE TITLE
require_passenger_gem necessary?

### ISSUE THREAD

**Issue by tamaloa** [barttenbrinke/munin-plugins-rails#18]
Hi,
we have systems using brightbox's ruby and libapache2-mod-passenger.
This means we do not have a passenger gem installed in the systems ruby.

Running passenger-memory-stats works without problems (as do the other passenger commands).

Is it necessary to require the passenger gem itself in / lib / munin / plugins / passenger_memory_stats.rb ?

**Comment by barttenbrinke** [comment]
The Munin plugin parses the output of the passenger-status binary to get it's values
https://github.com/barttenbrinke/munin-plugins-rails/blob/master/lib/munin/request_log_analyzer_plugin.rb#L77
As long as you have the binary on the system and the Munin plugin can find it, you do not need the have the passenger gem installed.
