### ISSUE TITLE
small typo in passenger_status

### ISSUE THREAD

**Issue by mschoolmaster** [barttenbrinke/munin-plugins-rails#3]
line 80:

graph_args --base 1000 -l 0 --upperlimit #{upper_limit}

should be 

graph_args --base 1000 -l 0 --upper-limit #{upper_limit}

as per: http://munin.projects.linpro.no/wiki/graph_args

Thanks for a killer plugin set!  Really appreciate you putting it all together.

**Comment by barttenbrinke** [comment]
Fixed :)
